name: Cloud-Native DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

# Global environments to enforce modern runtime settings
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  secret-scanning:
    name: Secret Auditing Gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          # Targets the entire directory layout if no branch delta is found
          path: ./
          extra_args: --only-verified

  static-analysis:
    name: SAST Flaw Scanning Gate
    runs-on: ubuntu-latest
    needs: secret-scanning
    container:
      image: semgrep/semgrep:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Semgrep Code Audit
        run: semgrep scan --config semgrep-rules.yaml --error